# Configuración del Servidor
server.port=8080

# Configuración de Base de Datos H2 (En memoria)
spring.datasource.url=jdbc:h2:mem:incidenciasdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=admin

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Inicialización de Datos (data.sql)
# Difiere la inicialización hasta que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Habilitar Consola H2 para depuración
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
